taxapp/urls.py
# urls.py
from django.urls import path

from.import views
from .views import *
app_name = "taxapp"


urlpatterns = [
    
    path('', views.home, name="home"),
    path('search/', views.search, name="search"),
    path('tinlist/', views.tinlist, name="tinlist"),
    path('notfound/', views.notfound, name="notfound"),
    path('cb/', views.cb, name="cb"),
    
    path('dashboard/', views.dashboard, name="dashboard"),
    path('bwise/', views.bwise, name="bwise"),
    path('bwise2/<str:bname>/', views.bwise2, name="bwise2"),
   
    path('search/', views.search_view2, name="search_view2"),
    path('search_view2', views.search_view2, name="search_view2"),
    path('search/search_view2', views.search_view2, name="search_view2"),
    path('cb2/<int:r>/', views.cb2, name="cb2"),
    path('admin/', views.admin, name="admin"),
    
]

taxproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('taxapp.urls')),
]

admin.site.index_title ="The Tax Checker"
admin.site.site_header ="The TIN Checker"
admin.site.site_title ="TIN CHK"




taxapp/models.py

from django.db import models

class Taxpayer(models.Model):
    name = models.CharField(max_length=255,null=True)
    nid = models.IntegerField(null=True)
    
    def __str__ (self):
            return self.name
        
class Citizen(models.Model):
    name = models.CharField(max_length=255,null=True)
    nid = models.IntegerField(null=True)
    
    def __str__ (self):
            return self.name
        

class Bank(models.Model):
    bname = models.CharField(max_length=255,null=True)
    nid = models.IntegerField(null=True)
    #nid = models.ForeignKey(Citizen,null=True,on_delete=models.CASCADE)
    acno = models.IntegerField(null=True)
    balance = models.IntegerField(null=True)
    cname = models.ForeignKey(Citizen,null=True,on_delete=models.CASCADE)
    def __str__ (self):
            return self.bname





  
    

  

taxapp/forms.py
from django import forms
from taxapp import models

class NidForm(forms.Form):
    nid = forms.IntegerField(required=True)

class Taxpayer(forms.ModelForm):
    class Meta:
        model = models.Taxpayer
        fields ="__all__"

taxapp/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.models import Group, User
from django.shortcuts import  redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
from django.contrib.auth.models import User, auth
from taxapp.forms import  Taxpayer
from django.http import HttpResponse
from .models import Taxpayer,Bank,Citizen
#========================================================= 
def notfound(request):
    nt=Taxpayer.objects.all()
    dict={"nontin": nt}
      
    return render(request,"notfound.html",context= dict)
#========================================================= 



def search_view2(request):
    
        t = Taxpayer.objects.all()
        dict = {'taxpayer': t,
                }
    
        if request.method == 'POST':
                
                input_nid = request.POST.get('nid')
                if  input_nid.isnumeric():
                    input_nid = int(input_nid)
                else:
                    error_msg = 'Invalid NID. Please enter a valid number.'
                    return render(request, 'search.html', {'error': error_msg})
                taxpayer = Taxpayer.objects.filter(nid=input_nid)
                dic={'taxpayer':taxpayer}
                if  taxpayer : 
                    message = " Found NID in Taxpayer list"
                    return render(request, 'all.html',{'taxpayer':taxpayer,'msg3': message})       
                else:    
                    msg = "NID not found in Taxpayer list"
                return render(request, 'search.html',{'tinlist':taxpayer,'msg1':msg})        
    
    
#===================================================
def home(request):
    t = Taxpayer.objects.all()
    
    return render(request, 'home.html',{'form':Taxpayer,'tinlist':t})     
#===================================================
def search(request):
    t = Taxpayer.objects.all()
    return render(request, 'search.html',{'form':Taxpayer,'tinlist':t})  
#=========================================================   
#===================================================
def dashboard(request):
    t = Taxpayer.objects.all()
    return render(request, 'dashboard.html',{'tinlist':t})  
#=========================================================    
def tinlist(request):
    t = Taxpayer.objects.all()    
    return render(request, 'tinlist.html',{'tinlist':t})       
#===================================================
def cb(request):#citizen wise bank report all citizen
    d = Bank.objects.all()
    c= Citizen.objects.all()    
    return render(request, 'cblist.html',{'cblist':d,'citizen':c})       
#===================================================    


def bwise(request):
    c= Bank.objects.all()
    #bname = Bank.objects.all().filter(bname='Asia').get(bname='Asia')
   
    data = {
        'bank': c,
       
    }
    return render(request, 'bwise.html', context=data)

# =========================================================   
def bwise2(request,bname):
    b= Bank.objects.all()
    c = Citizen.objects.all()
    #bname = Bank.objects.all().filter(bname='Asia').get(bname='Asia')
    bname= Bank.objects.all().filter(bname=bname)
    #bname = Bank.objects.all().filter(bname='Asia')
    data = {
        'citizen': c,
       'bname': bname,
       'b':b,
    }
    return render(request, 'bwise2.html', context=data)

# =========================================================      
def admin(request):
        return render(request, 'admin.site.urls')

#=========================================================          
def cb2(request, r):
        c = Citizen.objects.all()
       
        r= Bank.objects.all().filter(nid=r)
        #c= Citizen.objects.all()
       
        return render(request, 'cblist2.html', {'cb':r,'Bank':c})
                 
#citizen wise bank report all citizen
   
        
        #return render(request, 'cblist2.html',{'cblist':b,'citizen':c})     
            
 
     
       

    
      
  
       
            
            
        
          
     
  
  
        
     
       


templates/all.html
<!-- non_subscribers.html -->

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>   
        
        <title>Tin holder</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            table, th, td {
                border: 1px solid black;
            }
            table.center {
                margin-left: auto;
                margin-right: auto;
            }
            h1{
                text-align: center;
                color:blue;
                            }
            h3{
                text-align: center;
                color:red;
                        }
            a{
                text-align: center;
                color:red;
                        }  
            button{
                text-align: center;
                
                        }                      
        </style>
    </head>
    <body>
        <!--------------------Start navbar------------------------>
        <nav class="navbar navbar-expand-lg" style="background-color: #FFA07A;">
          <!--nav class="navbar navbar-expand-lg bg-dark"-->
            <div class="container-fluid">
              <a class="navbar-brand"href="" ></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="navbar-brand">
                    <a class="nav-link active" href="{% url 'taxapp:search' %}">Search</a>
                  </li>
                  <li class="navbar-brand">
                    <a class="nav-link active"href="{% url 'taxapp:dashboard' %}">Dashboard</a>
                  </li>
                 
                  
                 
                </ul>
                </div>
            </div>
          </nav>

  
        <!--------------------End navbar------------------------>
      
      <h1>{{msg3}}</h1>
      <br><h3 >TIN holder profile .</h3>
           <div>
             <br>
            {% for taxpayer in taxpayer %}
            <h1>Name :{{ taxpayer.name }}</h1><br>
            <h3 >NID : {{ taxpayer.nid }}</h3>
        {% endfor %}
                 

           </div>
  
           <div>
            {% for message in message %}
            <h3>{{message}}</h3>
            {% endfor %}
          </div>   
    </body>
</html>

templates/bwise.html

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
 <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>   
<title>Account list</title>
<style>
  table, th, td {
    border: 1px solid black;
  }
  table.center {
    margin-left: auto;
    margin-right: auto;
  }
  h1{
      text-align: center;
      color:blue;
                }
  h3{
    text-align: center;
    color:red;
              }
  a{
    text-align: center;
    color:red;
              }            
</style>
</head>


<body> 
  <br>
 <!--------------------Start navbar------------------------>
 <nav class="navbar navbar-expand-lg" style="background-color: #FFA07A;">
  <!--nav class="navbar navbar-expand-lg bg-dark"-->
    <div class="container-fluid">
      <a class="navbar-brand"href="" ></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="navbar-brand">
            <a class="nav-link active"href="{% url 'taxapp:dashboard' %}">Dashboard</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link active" href="{% url 'taxapp:search' %}">Search</a>
          </li>
         
        </ul>
        </div>
         
      
         
    </div>
  </nav>
  <!--------------------End navbar------------------------>
</br>
 
  <div>
    <br> 
    <h3> Bank  list </h3>
 
                         
              <table class="center" border="4" cellpadding="10"width="800" enctype="multipart/table-data" >
                  <tr>
                  <th >ID </th>
                  <th colspan>Bank</th>
                 
                  </tr>
                   {% for n in bank %}
                  <tr>
                  <td>{{n.pk}}</td>
                  <td><a href="{% url 'taxapp:bwise2' bname=n.bname %}">{{n.bname}}</li></a> </td>
                  </tr>
                  <br> 
                  {% endfor %}        
                         
                    

                    
                </table>             
               
              </div> 
              <br>       
              <div>
                {% for message in messages %}
                <h3>{{message}}</h3>
                {% endfor %}
               </div>         
                      
           

              </div>                                 
           
                 
        
           
  
  <br><br><br>

<!--------------------Footer Start------------------------>
<footer class="bg-success text-white position-relative">
  <p class="text-center">© Copyright 2022-2032 www.Soft Ray.io. All rights reserved. Developed by Soft Ray.</p>
</footer>
<!--------------------Footer End------------------------>
<br>
</body>
</html>











        

    

templates/cblist.html

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
 <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>   
<title>Account list</title>
<style>
  table, th, td {
    border: 1px solid black;
  }
  table.center {
    margin-left: auto;
    margin-right: auto;
  }
  h1{
      text-align: center;
      color:blue;
                }
  h3{
    text-align: center;
    color:red;
              }
              h4{
                text-align: center;
                color:blue;
                          }           
  a{
    text-align: center;
    color:red;
              }            
</style>
</head>


<body> 
  <br>
 <!--------------------Start navbar------------------------>
 <nav class="navbar navbar-expand-lg" style="background-color: #FFA07A;">
  <!--nav class="navbar navbar-expand-lg bg-dark"-->
    <div class="container-fluid">
      <a class="navbar-brand"href="" ></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="navbar-brand">
            <a class="nav-link active" href="{% url 'taxapp:search' %}">Search</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link active"href="{% url 'taxapp:dashboard' %}">Dashboard</a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
   
          
     
       
    
  
  <!--------------------End navbar------------------------>

 
  <div>
   
    <h3>All  Citizen all bank account list </h3>
    <h4>Click the Red NID and get all account and balance tag with that NID. </h4>
                         
              <table class="center" border="4" cellpadding="10"width="800" enctype="multipart/table-data" >
                  <tr>
                  <th >ID </th>
                  <th colspan>Bank</th>
                  <th colspan>Nid</th>
                  <th >AC No: </th>
                  <th colspan>Balance</th>
                  <th colspan>Citizen</th>
                  </tr>
                   {% for n in cblist %}
                  <tr>
                  <td>{{n.pk}}</td>
                  <td>{{n.bname}}</td>
                  <td><a href="{% url 'taxapp:cb2' r=n.nid %}">{{ n.nid }}</li></a> </td>
                 
                  <td>{{n.acno}}</td>
                  <td>{{n.balance}}</td>
                  
                  <td>{{ n.cname }} </td>
                  </tr>
                  <br> 
                  {% endfor %}        
                         
                 

                    
                </table>             
               
             
              <br>       
              <div>
                {% for message in messages %}
                <h3>{{message}}</h3>
                {% endfor %}
               </div>         
                      
           

              </div>                                 
           
                 
        
           
  
  <br><br><br>

<!--------------------Footer Start------------------------>
<footer class="bg-success text-white position-relative">
  <p class="text-center">© Copyright 2022-2032 www.Soft Ray.io. All rights reserved. Developed by Soft Ray.</p>
</footer>
<!--------------------Footer End------------------------>
<br>
</body>
</html>











        

    

templates/cblist2.html

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
 <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>   
<title>Account list</title>
<style>
  table, th, td {
    border: 1px solid black;
  }
  table.center {
    margin-left: auto;
    margin-right: auto;
  }
  h1{
      text-align: center;
      color:blue;
                }
  h3{
    text-align: center;
    color:red;
              }
  a{
    text-align: center;
    color:red;
              }            
</style>
</head>


<body> 
  <br>
 <!--------------------Start navbar------------------------>
 <nav class="navbar navbar-expand-lg" style="background-color: #FFA07A;">
  <!--nav class="navbar navbar-expand-lg bg-dark"-->
    <div class="container-fluid">
      <a class="navbar-brand"href="" ></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="navbar-brand">
            <a class="nav-link active"href="{% url 'taxapp:cb' %}">Back</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link active" href="{% url 'taxapp:search' %}">Search</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link active"href="{% url 'taxapp:dashboard' %}">Dashboard</a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
   
          
     
       
    
  
  <!--------------------End navbar------------------------>

 
  <div>
   
    <h3> All Bank account list against one NID </h3>
 
                         
              <table class="center" border="4" cellpadding="10"width="800" enctype="multipart/table-data" >
                  <tr>
                  <th >ID </th>
                  <th colspan>Bank</th>
                  <th colspan>Nid</th>
                  <th >AC No: </th>
                  <th colspan>Balance</th>
                  <th colspan>Citizen</th>
                  </tr>
                  {% for cb in cb %}
                  <tr>
                  <td>{{cb.pk}}</td>
                  <td>{{cb.bname}}</td>
                  <td> {{cb.nid}}</td>
                  <td>{{cb.acno}}</td>
                  <td>{{cb.balance}}</td>
                  <td>{{cb.cname}}</td>
                  </tr>
                  <br> 
                  {% endfor %}  
                         
                    

                    
                </table>             
               
              </div> 
              <br>       
                 
                      
           

              </div>                                 
           
                 
        
           
  
  <br><br><br>

<!--------------------Footer Start------------------------>
<footer class="bg-success text-white position-relative">
  <p class="text-center">© Copyright 2022-2032 www.Soft Ray.io. All rights reserved. Developed by Soft Ray.</p>
</footer>
<!--------------------Footer End------------------------>
<br>
</body>
</html>











        

    

templates/dashboard.html

<!DOCTYPE html>



{% load static %}



<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
 <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>   
<title>Result</title>
<style>
  table, th, td {
    border: 1px solid black;
  }
  table.center {
    margin-left: auto;
    margin-right: auto;
  }
  h1{
      text-align: center;
      color:blue;
                }
  h3{
    text-align: center;
    color:red;
              }
  a{
    text-align: center;
    color:red;
              }  
              
              #Hello-msg{
                fontsize:18px;
                color:#FFFFFF;
                margin-left:20px;
              }
              #carddenger{
                
                color:#FFFFFF;
                
                }
              #card{
                fontsize:18px;
                display: flex;  
                margin-top:20px;
                margin-left:20px;
                }
                        
              
                button{
                  text-align: center;
                  
                            }              

</style>
</head>


<body> 
  <br>
 <!--------------------Start navbar------------------------>
 <nav class="navbar navbar-expand-lg" style="background-color: #FFA07A;">
  <!--nav class="navbar navbar-expand-lg bg-dark"-->
    <div class="container-fluid">
      <a class="navbar-brand"href="" ></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="navbar-brand">
            <a class="nav-link active" href="{% url 'taxapp:search' %}">Search</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link active" href="{% url 'taxapp:cb' %}">All ac and clint</a>
          </li>
          <!--li class="navbar-brand">
            <a class="nav-link active" href="">Clint wise bank</a>
          </li-->
          <li class="navbar-brand">
            <a class="nav-link active" href="{% url 'taxapp:bwise' %}">Bank wise client</a>
          </li>
          <li class="navbar-brand">
            <a class="nav-link active" href="{% url 'taxapp:admin' %}">Admin login</a>
          </li>
         
        </ul>
        </div>
    </div>
  </nav>
  <!--------------------End navbar------------------------>
</br>
                         
      <h1 >Hello {{ request.user }}   Welcome to Your Dashboard.</h1><br>
    <h3 > For login to admin panel:</h3>
    <h3 > username: First</h3>
    <h3 >Password: @abcde12345</h3>
    {% if request.user.is_staff %}
             
              <div class="container text-center">
                  <div class="row row-cols-4"> 
                     
             
                  <div class="card text-bg-primary mb-3"id="card" style="max-width: 15rem;">
                      
                    <div class="card-header">All citizen all bank</div>
                      <div class="card-body">
                         <!--h5 class="card-title">Primary card title</h5-->
                        <h5> <a href="{% url 'taxapp:cb' %}"class="card-title">Click here</a></h5>
                        <p class="card-text">All citizen all bank.</p>
                    </div>
                  </div>
                  
                       
                     
                <div class="card text-bg-secondary mb-3"id="card" style="max-width: 15rem;">
                  <div class="card-header">TIN holder list</div>
                  <div class="card-body">
                    <h5> <a href="{% url 'taxapp:tinlist' %}"class="card-title">Click here</a></h5>
                    <p class="card-text">TIN holder list</p>
                  </div>
                </div>
               
               
                <div class="card text-bg-warning mb-3"id="card" style="max-width: 15rem;">
                  <div class="card-header">Bank list</div>
                  <div class="card-body">
                    <h5> <a href="{% url 'taxapp:bwise' %}"class="card-title">Click here</a></h5>
                    <p class="card-text"> Bank list</p>
                  </div>
                </div>
                
                
                 
                <div class="card text-bg-success mb-3"id="card" style="max-width: 15rem;">
                  <div class="card-header">Admin dashboard </div>
                    <div class="card-body">
                      <h5> <a href="{% url 'taxapp:admin' %}"class="card-title">Click here</a></h5>
                      
                      <p class="card-text">Admin panel login</p>
                    </div>
                 </div>
              </div>
          </div>
          {% endif %}
      <br>
      
      
           
      
  
  
  <br><br><br><br><br><br><br><br><br><br><br><br><br>    

  
<!--------------------Footer Start------------------------>
<footer class="bg-success text-white position-relative">
  <p class="text-center">© Copyright 2022-2032 www.Soft Ray.io. All rights reserved. Developed by Soft Ray.</p>
</footer>
<!--------------------Footer End------------------------>
<br>
</body>
</html>











        

    

templates/notfound.html
<!-- non_subscribers.html -->

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>   
        
        <title>Non Tin</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <style>
            table, th, td {
                border: 1px solid black;
            }
            table.center {
                margin-left: auto;
                margin-right: auto;
            }
            h1{
                text-align: center;
                color:#12225D;
                            }
            h3{
                text-align: center;
                color:red;
                        }
            a{
                text-align: center;
                color:red;
                        }  
            button{
                text-align: center;
                
                        }                      
        </style>
    </head>
    <body>
        <!--------------------Start navbar------------------------>
    <nav class="navbar navbar-expand-lg" style="background-color: #FFA07A;">
        <!--nav class="navbar navbar-expand-lg bg-dark"-->
          <div class="container-fluid">
            <a class="navbar-brand"href="" ></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
           
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            
            </button>
            
            <a class="navbar-brand"<a href=""> </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
               
                <li class="navbar-brand">
                  <a class="nav-link active"href="{% url 'taxapp:dashboard' %}">Dashboard</a>
                </li>
                <li class="navbar-brand">
                  <a class="nav-link active"href="">All NID</a>
                </li>
              </ul>
              </div>
          </div>
        </nav>
        <!--------------------End navbar------------------------>
      <br><h1 >Not found in TIN holder list .</h1>
      <h1 > </h1>
      <h1 >Let us help the citizen to be a TIN holder.</h1>
      
            
    </body>
</html>